// ============================================================================
//  enrich.js — Stage 3 (AI): turn a plain intake into richer docs content.
//
//  One structured-output Claude call (raw fetch, no SDK) that returns:
//   - a Mermaid architecture diagram (from the locked decisions),
//   - a Mermaid Gantt (from the milestones),
//   - Given/When/Then acceptance criteria per requirement,
//   - full ADR bodies (context / trade-off / revisit) per decision.
//  render-intake injects these into the generated pages.
// ============================================================================
'use strict';

const fs = require('fs');
const path = require('path');

const API_URL = 'https://api.anthropic.com/v1/messages';
const MODEL = process.env.WIZARD_MODEL || 'claude-opus-4-8';

// Per-call OUTPUT budgets. Opus 4.8 accepts up to ~128k output tokens, so the old
// 32k was self-imposed. The docs pass and EACH per-milestone plan call get a generous
// cap so detail is never cut to fit. (Input is the 1M context — never the constraint.)
const DOCS_MAX_TOKENS = Number(process.env.DOCS_MAX_TOKENS) || 48000;
const PLAN_MAX_TOKENS = Number(process.env.PLAN_MAX_TOKENS) || 64000;

// Governance phase labels — must match lib/linear.js GOV_LABELS.
const GOV_LABELS = ['gov:owner-action', 'gov:phase-01-requirements', 'gov:phase-02-architecture', 'gov:phase-03-design', 'gov:phase-04-implementation', 'gov:phase-05-review', 'gov:phase-06-testing', 'gov:phase-07-release'];

const str = (d) => ({ type: 'string', description: d });
const obj = (p, r) => ({ type: 'object', additionalProperties: false, properties: p, required: r });
const arr = (items, d) => ({ type: 'array', description: d, items });

// The build plan is generated by its OWN focused AI call(s) (enrichPlan) — in fact
// ONE call PER MILESTONE — so each milestone's issues get the full output budget and
// detail is never cut to fit. ISSUE_OBJ is the per-issue schema, reused by both the
// per-milestone call and the whole-plan fallback.
const ISSUE_OBJ = obj({
  title: str('A concrete, narrowly-scoped Linear issue title — ONE shippable thing (a single feature, endpoint, screen, table/migration, integration, or setup task)'),
  owner: { type: 'string', enum: ['Human', 'AI'], description: 'Who does it. "Human" = work only a person can do: creating accounts/signups, minting API keys & secrets, DNS/domain/billing/payment-provider/OAuth setup, approvals, manual verification. "AI" = code/docs/tests/migrations a coding agent writes. EVERY project has several Human setup tasks — identify them; never default everything to AI.' },
  objective: str('One sentence: what this task accomplishes'),
  steps: arr(str('One concrete, self-contained step. HUMAN: a fully click-by-click action a non-technical person can follow blind — the exact site/screen, the button/menu by name, what to type, the precise value to copy and where to paste it, and how to confirm it worked. AI: a precise, imperative build instruction — the exact file(s)/module(s) to create or change, the functions/endpoints/data shapes, the approach, libraries, commands, and edge cases.'), 'The COMPLETE ordered step-by-step for THIS task — NEVER empty and never just the objective restated. Use as many steps as it genuinely needs (a small atomic task 3–6; a meatier one 6–12).'),
  notes: str('Deep execution detail beyond the steps. AI: technical approach, files/modules/functions, data shapes & schemas, libraries (+ versions), commands, how to test, gotchas/failure modes — production-quality first pass. HUMAN: prerequisites, direct links, account/permission needs, pitfalls. Markdown allowed.'),
  doneWhen: str('The acceptance check — how you know this task is complete and correct'),
  label: { type: 'string', enum: GOV_LABELS, description: 'The governance phase this task belongs to' },
}, ['title', 'owner', 'objective', 'steps', 'notes', 'doneWhen', 'label']);
const ISSUES_DESC = 'The atomic sub-issues in build order — MULTIPLE per milestone (one per discrete requirement/feature/deliverable, PLUS the phase tasks: setup, schema/migration, implementation, tests, review, release). A milestone with real scope has SEVERAL issues; never collapse it into one mega-issue.';
const PLAN_PROP = arr(obj({
  milestone: str('The EXACT intake milestone name this group of work belongs to'),
  issues: arr(ISSUE_OBJ, ISSUES_DESC),
}, ['milestone', 'issues']), 'Every intake milestone broken into atomic, governance-phased sub-issues. Cover EVERY requirement (each → one or more issues) and add the setup/architecture/review/testing/release tasks a disciplined team would, including the Human owner-action setup (accounts, keys, DNS, billing).');

const ENRICH_SCHEMA = obj({
  architecture: obj({
    layers: arr(obj({
      label: str('The layer label shown on the left edge, e.g. "User", "DNS · Cloudflare", "Edge", "Data · Auth · Payments", "Side services · Backups", "CI / CD". Order layers top→bottom: people/clients first, then edge/CDN, the application, data/auth/payments, side services, and the CI/CD pipeline last.'),
      nodes: arr(obj({
        id: str('a short unique lowercase id, e.g. "app", "neon", "ghactions"'),
        title: str('the node title, e.g. "Fly.io · sequenceapp.life" or "Neon · Postgres 15"'),
        eyebrow: str('a small label above the title, e.g. "Our app · Fly.io" or "Third-party · Clerk", or "" '),
        lines: arr(str('a plain detail line (tech/config)'), 'detail lines under the title (no bullet)'),
        bullets: arr(str('a key specific'), 'bullet specifics, shown with a • '),
        subs: arr(obj({ head: str('sub-box heading, e.g. "Middleware" or "Endpoints"'), lines: arr(str('a line'), 'lines in the sub-box') }, ['head', 'lines']), 'optional sub-boxes inside this node (e.g. the application\'s Middleware + Endpoints)'),
        cls: { type: 'string', enum: ['actor', 'edge', 'app', 'saas', 'data', 'infra'], description: 'actor=users; edge=CDN/DNS/proxy; app=OUR app/runtime; saas=third-party SaaS; data=databases/stores; infra=CI/CD/registry/deploy' },
      }, ['id', 'title', 'cls']), 'nodes in this layer, left→right'),
    }, ['label', 'nodes']), 'The ordered architectural layers, top→bottom. Technically precise (tech + version + ADR + key specifics, incl. the app\'s middleware/endpoints as subs), grounded in the locked decisions and the real codebase — but CONCISE like a clean reference diagram so each box stays compact: the people (User, Developer, Claude Code) get exactly ONE short descriptor line (e.g. "Browser · Mobile · PWA", "Builds & ships the app", "AI coding agent") and NO bullets; service nodes get at most 1–3 short lines plus at most 4 short bullets. Tight, not verbose.'),
    edges: arr(obj({
      from: str('source node id'), to: str('target node id'),
      label: str('a short edge label, e.g. "HTTPS", "verify JWT", "webhook", "deploy", or ""'),
      kind: { type: 'string', enum: ['default', 'critical', 'webhook', 'backup', 'deploy'] },
    }, ['from', 'to']), 'connections between node ids — the runtime data flows, the CI/CD pipeline chain, and the deploy edge into the application.'),
  }, ['layers']),
  architectureNote: str('1–2 sentences describing the architecture in plain language.'),
  ganttMermaid: str('A Mermaid `gantt` chart from the milestones (use each milestone name as a section/task; derive durations from targets like "Week 2"). Valid Mermaid only, no code fences.'),
  stackComponents: arr(obj({
    category: str('The role in the stack, e.g. "App host", "Database", "Auth", "Payments", "Marketing", "Email", "Errors", "Registry", "Backups", "CI/CD".'),
    component: str('The chosen product/tech, e.g. "Fly.io", "Neon", "Clerk".'),
    detail: str('A terse, technical one-liner of the key specifics, e.g. "Managed Postgres 15 · pooled · main + dev branch".'),
    adr: str('The matching ADR concern label to link (match an intake decision\'s concern), or "" if none.'),
  }, ['category', 'component', 'detail']), 'EVERY component of the stack as a labeled row, like a senior architect\'s "Stack components" table. Cover the locked decisions AND the supporting services the architecture implies (CDN, email, error-tracking, registry, backups, CI/CD).'),
  requestFlows: arr(obj({
    title: str('The flow name, e.g. "Sign up + first session", "Pay for a subscription", "Production deploy", "Backup + disaster recovery".'),
    status: str('A 1–3 word status tag, e.g. "live", "every merge", "planned".'),
    body: str('A precise TECHNICAL narrative of the end-to-end flow: the services touched, the real endpoints, and what happens at each step (2–4 sentences). You may use `code` for endpoints/identifiers.'),
  }, ['title', 'status', 'body']), 'The KEY request/operational flows end-to-end (sign-up, payment, billing, deploy, backup) — concrete and technical, naming the real endpoints and services.'),
  requirements: arr(obj({
    title: str('The requirement title, matched to the intake'),
    priority: { type: 'string', enum: ['Must', 'Should', 'May', "Won't"] },
    given: str('Given … (precondition)'),
    when: str('When … (the action)'),
    then: str('Then … (the observable outcome; may include " And …" lines separated by \\n)'),
  }, ['title', 'priority', 'given', 'when', 'then']), 'One Given/When/Then acceptance criterion per intake requirement, in the same order'),
  adrs: arr(obj({
    concern: str('The decision concern, matched to the intake'),
    choice: str('The decision'),
    context: str('Why this decision needed making (the forces)'),
    tradeoff: str('The trade-off accepted by choosing it'),
    revisit: str('The trigger that would make us revisit this decision'),
  }, ['concern', 'choice', 'context', 'tradeoff', 'revisit']), 'One ADR body per intake decision, in the same order'),
}, ['architecture', 'architectureNote', 'ganttMermaid', 'stackComponents', 'requestFlows', 'requirements', 'adrs']);

const SYSTEM =
  'You expand a software project plan into richer documentation and a governance-phased build runbook. You are given the project intake (product, requirements, decisions, milestones) and, when available, excerpts of the existing/related codebase. Produce: a DETAILED, reference-quality architecture as structured LAYER DATA (the `architecture` field — ordered top→bottom layers of detailed nodes, plus edges), grounded in the locked decisions and the real codebase. The TOP "User" lane holds the end User AND the Developer + Claude Code (the AI coding agent); lower lanes are the category layers (Edge, Application, Data·Auth·Payments, Side services, CI/CD). Draw the dev pipeline as edges — Developer → Claude Code → GitHub → registry → deploy → the app — alongside the runtime data flows. Nodes carry tech + version + ADR + bullet specifics (the application also gets middleware/endpoints sub-boxes), exactly as the architecture field describes; a "Stack components" list covering every component (decisions + supporting services); the KEY request/operational flows end-to-end (sign-up, payment, billing, deploy, backup) as concrete technical narratives; a Mermaid Gantt from the milestones; one Given/When/Then acceptance criterion per requirement (concrete and observable — an actor and an outcome, never implementation detail); and a full ADR body per decision (context, trade-off accepted, revisit trigger). (The build plan / Linear issues are produced by a separate call — do not output a plan here.)\n\n' +
  'Be detailed and faithful to the intake and the code; do not invent scope. Output Mermaid as raw diagram source with NO code fences and NO surrounding markdown.';

function buildUserContent(intake, corpus) {
  const slim = {
    product: intake.product || {},
    requirements: (intake.requirements || []).map((r) => ({ title: r.title, priority: r.priority, test: r.test })),
    decisions: (intake.decisions || []).map((d) => ({ concern: d.concern, choice: d.choice, why: d.why })),
    milestones: (intake.milestones || []).map((m) => ({ name: m.name, done: m.done, target: m.target })),
    scalability: intake.scalability || [],
  };
  let out = 'Project intake:\n\n' + JSON.stringify(slim, null, 2) +
    '\n\nProduce the enrichment. Keep requirements and adrs in the SAME ORDER and titled the same as the intake. In `plan`, use the EXACT milestone names from the intake.';
  if (corpus && corpus.text) {
    out += '\n\n--- EXISTING CODE (' + corpus.includedCount + ' of ' + corpus.fileCount + ' uploaded files' + (corpus.truncated ? ', truncated' : '') + ') — use it to ground the diagram, decisions, and tasks ---\n' + corpus.text;
  }
  return out;
}

function aiEnabled() { return !!process.env.ANTHROPIC_API_KEY; }

// POST to the Claude API with retry-with-backoff on TRANSIENT failures (rate
// limits + Anthropic-side overload/5xx + network blips). 503/529 = overloaded,
// common for large Opus requests, and almost always succeeds on a retry. Honors a
// Retry-After header when present; otherwise exponential backoff with jitter.
// Throws (with .status) on non-retryable errors or once retries are exhausted.
const TRANSIENT_STATUS = new Set([429, 500, 502, 503, 529]);
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
const backoffMs = (attempt) => Math.min(30000, 1500 * Math.pow(2, attempt)) + Math.floor(Math.random() * 600);
async function claudeFetch(apiKey, body) {
  const MAX = Number(process.env.ENRICH_RETRIES) || 4;
  const TIMEOUT = Number(process.env.ENRICH_TIMEOUT_MS) || 600000;
  let lastErr = null;
  for (let attempt = 0; attempt <= MAX; attempt++) {
    const ctrl = new AbortController();
    const timer = setTimeout(() => ctrl.abort(), TIMEOUT);
    let res;
    try {
      res = await fetch(API_URL, {
        method: 'POST',
        headers: { 'x-api-key': apiKey, 'anthropic-version': '2023-06-01', 'content-type': 'application/json' },
        body: JSON.stringify(body), signal: ctrl.signal,
      });
    } catch (e) {
      clearTimeout(timer);
      if (e.name === 'AbortError') { const err = new Error('the AI build timed out'); err.status = 504; throw err; }
      lastErr = new Error('could not reach the Claude API: ' + e.message); lastErr.status = 503;
      if (attempt < MAX) { await sleep(backoffMs(attempt)); continue; }
      throw lastErr;
    }
    if (res.ok) { const d = await res.json().catch(() => null); clearTimeout(timer); return d; }
    const retryAfter = Number(res.headers.get('retry-after'));
    clearTimeout(timer);
    if (TRANSIENT_STATUS.has(res.status) && attempt < MAX) {
      lastErr = new Error('Claude API HTTP ' + res.status + ' (transient)');
      await sleep(retryAfter > 0 ? retryAfter * 1000 : backoffMs(attempt));
      continue;
    }
    const data = await res.json().catch(() => null);
    const err = new Error((data && data.error && data.error.message) || ('Claude API HTTP ' + res.status)); err.status = res.status; throw err;
  }
  throw lastErr || new Error('Claude API request failed');
}

async function enrich(intake, apiKey, corpus, onProgress) {
  apiKey = (apiKey && String(apiKey).trim()) || process.env.ANTHROPIC_API_KEY;
  if (!apiKey) { const e = new Error('no Claude API key provided'); e.code = 'no_key'; throw e; }
  noteProgress(onProgress, 'Generating architecture, requirements & ADRs');

  const body = {
    model: MODEL,
    max_tokens: DOCS_MAX_TOKENS,
    system: SYSTEM,
    output_config: { format: { type: 'json_schema', schema: ENRICH_SCHEMA }, effort: 'medium' },
    messages: [{ role: 'user', content: planContext(intake, corpus) }],
  };
  // A rich build (max_tokens 32k on Opus, plus a large code corpus) can run well
  // past 4 min and may hit transient overload — claudeFetch retries with backoff.
  const data = await claudeFetch(apiKey, body);
  usageOf(data, 'docs (architecture/reqs/ADRs)', DOCS_MAX_TOKENS);
  if (data && data.stop_reason === 'refusal') { const err = new Error('the model declined this request'); err.status = 422; throw err; }
  const text = ((data && data.content) || []).filter((b) => b.type === 'text').map((b) => b.text).join('');
  let parsed;
  try { parsed = JSON.parse(text); } catch { const err = new Error('could not parse the AI output'); err.status = 502; throw err; }
  // The architecture diagram is now structured DATA (layers + edges) rendered by
  // a deterministic swim-lane renderer, so no layout-refinement pass is needed.
  return sanitize(parsed);
}

// The design rules the diagram must satisfy — shared by the generator prompt and
// the refinement pass below.
const ARCH_RULES =
  'A DETAILED, reference-quality Mermaid `flowchart TB` drawn as stacked LAYERS, top → bottom. ' +
  '(1) Top row = the people: a "User" node (end user) and a "Developer" node, plain nodes side by side, NOT wrapped in a subgraph box. ' +
  '(2) One `subgraph` per layer, each with `direction LR` — typically "Edge" (DNS · CDN · marketing), "Application", "Data · Auth · Payments", "Side services" (email · errors · backups, if used), and "CI / CD". ' +
  '(3) Node labels are DETAILED and technically precise via <br/>: name; concrete tech + version; the relevant ADR; then 2–4 "• " bullet lines of key specifics. Do NOT dumb it down — engineers read this. The "Application" node also surfaces its key middleware and main endpoints as bullets. ' +
  '(4) Show the dev/CI pipeline as a chain: Developer → Claude Code → GitHub (repo + Actions) → container registry → deploy (flyctl rolling release) → the Application, with labeled edges. ' +
  '(5) Show the runtime path: User → Edge → Application → Data·Auth·Payments, with protocol-labeled edges (HTTPS · JWT verify · SQL · webhook). ' +
  '(6) Every node gets exactly one style class via `class <id> <class>` from: actor (User, Developer), edge, app, saas (incl. Claude Code), data, infra (GitHub/CI/registry/deploy). ' +
  '(7) Information-rich but balanced and uncrossed. No `classDef`/`style` lines. Valid Mermaid only — no code fences, no prose.';

const REFINE_SYSTEM =
  'You are a senior software architect and information designer. You refine Mermaid architecture diagrams for LAYOUT, BALANCE, GROUPING, and CLARITY without changing their technical accuracy. You output only valid Mermaid — no code fences, no commentary.';

const REFINE_SCHEMA = { type: 'object', additionalProperties: false, required: ['mermaid'],
  properties: { mermaid: { type: 'string', description: 'The refined Mermaid flowchart source — no code fences.' } } };

// Focused Opus pass that polishes the diagram's design. Any failure returns the
// original diagram unchanged, so the build never regresses on this.
async function refineArch(mmd, intake, apiKey) {
  apiKey = (apiKey && String(apiKey).trim()) || process.env.ANTHROPIC_API_KEY;
  mmd = String(mmd || '').trim();
  if (!apiKey || !mmd) return mmd;
  const prod = (intake && intake.product) || {};
  const userMsg = 'Refine this architecture diagram for ' + (prod.name || 'the product') +
    ' so it is clean, compact, balanced, and well-designed. Keep it technically faithful — improve grouping, layer ordering, spacing/balance, label wording, and reduce crossing edges. Make sure it satisfies EVERY rule.\n\n' +
    ARCH_RULES + '\n\nCURRENT DIAGRAM:\n' + mmd + '\n\nReturn ONLY the improved Mermaid in the `mermaid` field.';
  const body = {
    model: MODEL, max_tokens: 6000, system: REFINE_SYSTEM,
    output_config: { format: { type: 'json_schema', schema: REFINE_SCHEMA }, effort: 'high' },
    messages: [{ role: 'user', content: userMsg }],
  };
  const ctrl = new AbortController();
  const timer = setTimeout(() => ctrl.abort(), Number(process.env.ENRICH_TIMEOUT_MS) || 600000);
  try {
    const res = await fetch(API_URL, { method: 'POST', headers: { 'x-api-key': apiKey, 'anthropic-version': '2023-06-01', 'content-type': 'application/json' }, body: JSON.stringify(body), signal: ctrl.signal });
    const data = await res.json().catch(() => null);
    if (!res.ok) return mmd;
    const text = ((data && data.content) || []).filter((b) => b.type === 'text').map((b) => b.text).join('');
    let parsed; try { parsed = JSON.parse(text); } catch (e) { return mmd; }
    const refined = fence(parsed && parsed.mermaid);
    return (refined && /flowchart/i.test(refined)) ? refined : mmd;   // sanity-gate
  } catch (e) { return mmd; }
  finally { clearTimeout(timer); }
}

// Strip stray code fences the model sometimes wraps Mermaid in, and clamp shapes.
function fence(s) {
  return String(s || '').replace(/^\s*```[a-z]*\s*/i, '').replace(/```\s*$/i, '').trim();
}
function sanitize(p) {
  p = p || {};
  return {
    architectureMermaid: fence(p.architectureMermaid),
    architecture: (p.architecture && Array.isArray(p.architecture.layers)) ? { layers: p.architecture.layers, edges: Array.isArray(p.architecture.edges) ? p.architecture.edges : [] } : { layers: [], edges: [] },
    architectureNote: String(p.architectureNote || '').trim(),
    stackComponents: Array.isArray(p.stackComponents) ? p.stackComponents : [],
    requestFlows: Array.isArray(p.requestFlows) ? p.requestFlows : [],
    ganttMermaid: fence(p.ganttMermaid),
    requirements: Array.isArray(p.requirements) ? p.requirements : [],
    adrs: Array.isArray(p.adrs) ? p.adrs : [],
    plan: Array.isArray(p.plan) ? p.plan : [],
  };
}

// Focused, faster pass: regenerate ONLY the architecture (layers + edges + note).
// Used by the deployed editor's Assess so changing a decision (e.g. the database)
// also updates the diagram — not just the text — for review before committing.
async function enrichArchitecture(intake, apiKey, corpus) {
  apiKey = (apiKey && String(apiKey).trim()) || process.env.ANTHROPIC_API_KEY;
  if (!apiKey) return null;
  const schema = obj({ architecture: ENRICH_SCHEMA.properties.architecture, architectureNote: ENRICH_SCHEMA.properties.architectureNote }, ['architecture', 'architectureNote']);
  const body = {
    model: MODEL, max_tokens: 8000,
    system: 'You are a senior software architect. Produce ONLY the system architecture as structured layer data (the `architecture` field) plus a one-line note, exactly per the field descriptions. The CURRENT locked decisions are the SOURCE OF TRUTH — if a decision was just changed (e.g. the database swapped from Postgres to Oracle), the diagram MUST reflect the NEW choice and its implications, even if the existing code in the corpus still references the old one. Be technically precise and CONCISE like a clean reference diagram (the people get one line, no bullets). The top "User" lane holds the end User + Developer + Claude Code; lower lanes are the category layers; draw the dev pipeline + runtime flows as edges.',
    output_config: { format: { type: 'json_schema', schema: schema }, effort: 'high' },
    messages: [{ role: 'user', content: buildUserContent(intake, corpus) }],
  };
  const data = await claudeFetch(apiKey, body);
  const text = ((data && data.content) || []).filter((b) => b.type === 'text').map((b) => b.text).join('');
  const parsed = JSON.parse(text);
  if (!parsed || !parsed.architecture || !Array.isArray(parsed.architecture.layers)) return null;
  return { architecture: { layers: parsed.architecture.layers, edges: Array.isArray(parsed.architecture.edges) ? parsed.architecture.edges : [] }, architectureNote: String(parsed.architectureNote || '').trim() };
}

// Dedicated build-plan pass — its OWN full output budget, so the issues come out
// granular (many atomic sub-issues per milestone), properly owner-split, and fully
// step-by-step instead of starving at the tail of the big docs enrichment.
const PLAN_SYSTEM =
  'You are a senior tech lead turning a project intake into a COMPLETE, governance-phased build backlog of Linear issues. You are given the product, requirements, locked decisions, milestones, and (when available) the codebase.\n\n' +
  'Produce ONLY the `plan`: every intake milestone broken into ATOMIC sub-issues. Be GRANULAR — one issue per discrete deliverable (a single feature, endpoint, screen, table/migration, integration, or setup task), NOT one big issue per milestone. Cover EVERY requirement (each maps to one or more issues) and add the phase tasks a disciplined team always has: project/repo setup, schema & migrations, each feature, tests, review, release. A real milestone has SEVERAL issues — usually 4–10.\n\n' +
  'Split owners correctly. Mark as HUMAN every task only a person can do — creating accounts/signups, minting API keys & secrets, DNS/domain/billing/payment-provider/OAuth-app setup, approvals, manual verification. Every project has a handful (usually clustered in the early setup milestone). Mark as AI the code/docs/tests/migrations a coding agent writes. Do NOT default everything to AI.\n\n' +
  'Make EACH issue a complete, self-contained runbook entry — NEVER just an objective. Give: a one-sentence objective; the FULL ordered steps (HUMAN → click-by-click a non-technical person can follow blind; AI → a mini-spec naming the exact files/modules/functions, data shapes, libraries, commands, tests, and edge cases); deep execution notes; a done-when acceptance check; and the single best governance label. An issue with empty steps is unacceptable.\n\n' +
  'Be faithful to the intake and the code; do not invent scope. The issue is kicked off by a human telling Claude `start <issue-id>`, so steps must be directly actionable.';

function usageOf(data, label, max) {
  const u = (data && data.usage) || {};
  const rec = { pass: label, input: u.input_tokens || 0, output: u.output_tokens || 0, max: max, stop: (data && data.stop_reason) || null };
  rec.truncated = rec.stop === 'max_tokens';   // hit the output cap → detail WAS cut
  rec.headroomPct = max ? Math.round((1 - rec.output / max) * 100) : null;
  console.log('[enrich] ' + label + ': in=' + rec.input + ' out=' + rec.output + '/' + max +
    ' (' + rec.headroomPct + '% headroom) stop=' + rec.stop + (rec.truncated ? '  ⚠️ TRUNCATED' : ''));
  return rec;
}

// The project-agnostic 7-phase governance LIBRARY (the development process every
// issue must fit) lives as HTML in docs-kit.js. Strip it to text ONCE and feed the
// FULL library into every plan + cohesion call — grounding issues in the process.
let _govText = null;
function governanceText() {
  if (_govText !== null) return _govText;
  try {
    const src = fs.readFileSync(path.join(__dirname, 'docs-kit.js'), 'utf8');
    const entries = src.match(/"governance\/library\/0[0-7][^"]*":\s*"((?:[^"\\]|\\.)*)"/g) || [];
    _govText = entries.map((s) => {
      let html = '';
      try { html = JSON.parse(s.slice(s.indexOf(':') + 1).trim()); } catch (e) { return ''; }
      return html
        .replace(/<style[\s\S]*?<\/style>/gi, ' ').replace(/<script[\s\S]*?<\/script>/gi, ' ')
        .replace(/<\/(p|h[1-6]|li|tr|section|div)>/gi, '\n').replace(/<li[^>]*>/gi, '\n• ')
        .replace(/<[^>]+>/g, ' ').replace(/&[a-z]+;/gi, ' ')
        .replace(/[ \t]+/g, ' ').replace(/\n[ \t]*\n[ \t]*\n+/g, '\n\n').trim();
    }).filter(Boolean).join('\n\n———\n\n');
  } catch (e) { _govText = ''; }
  return _govText;
}

// The full reference context fed to EVERY plan + cohesion call: the whole intake
// (product, ALL requirements/decisions/milestones), the whole uploaded codebase, and
// the FULL governance library. Quality-over-speed: we deliberately fill the 1M input
// window so the model has everything it needs to be right the first time.
function planContext(intake, corpus) {
  let c = buildUserContent(intake, corpus);
  const gov = governanceText();
  if (gov) c += '\n\n=== GOVERNANCE LIBRARY — the 7-phase development process EVERY issue must fit. Label each issue with the correct gov:phase, and make sure each milestone honors the phases (requirements → architecture → design → implementation → review → testing → release) ===\n' + gov;
  return c;
}

function noteProgress(onProgress, msg) { console.log('[enrich] ▶ ' + msg); if (typeof onProgress === 'function') { try { onProgress(msg); } catch (e) {} } }

// Generate the build plan ONE MILESTONE AT A TIME so each milestone's issues get the
// full PLAN_MAX_TOKENS output budget — detail is never cut to share a budget. Returns
// { plan, usage } where usage has a per-call token record (so we can prove no pass
// hit the cap). If a milestone ever does truncate, raise PLAN_MAX_TOKENS or it gets
// auto-flagged in usage.
async function enrichPlan(intake, apiKey, corpus, onProgress) {
  apiKey = (apiKey && String(apiKey).trim()) || process.env.ANTHROPIC_API_KEY;
  if (!apiKey) return { plan: [], usage: [], review: null };
  const milestones = (intake.milestones || []).filter((m) => m && (m.name || m.done));
  const usage = [];
  const ctx = planContext(intake, corpus);   // full intake + full codebase + full governance library
  const issuesSchema = obj({ issues: arr(ISSUE_OBJ, ISSUES_DESC) }, ['issues']);

  // Each per-milestone call sees the FULL reference context AND the FULL detail of
  // every issue already created — so it never duplicates them, builds on/references
  // them, and the seam between milestones stays clean.
  const callFor = async (m, priorIssues, idx, total) => {
    noteProgress(onProgress, 'Planning milestone ' + idx + '/' + total + ': ' + m.name);
    const priorBlock = priorIssues.length
      ? '\n\n=== ALREADY CREATED in earlier milestones — FULL detail. Do NOT duplicate any of these; assume they exist, build on and reference them ===\n' +
        JSON.stringify(priorIssues, null, 2)
      : '';
    const focus = '\n\n=== YOUR TASK ===\nGenerate ONLY the atomic sub-issues for the milestone "' + m.name + '"' +
      (m.done ? ' (done means: ' + m.done + ')' : '') + '.\n' +
      'Cover its full scope: every requirement it implies, plus the governance-phase tasks that belong to it ' +
      '(setup, schema/migrations, each feature, integration, tests, review, release — whichever apply). ' +
      'Be EXHAUSTIVE and granular — you have a full budget; never hold back detail. Ground every issue in the ' +
      'codebase and governance library above. Do NOT include work that belongs to the other milestones.' + priorBlock;
    const body = {
      model: MODEL, max_tokens: PLAN_MAX_TOKENS, system: PLAN_SYSTEM,
      output_config: { format: { type: 'json_schema', schema: issuesSchema }, effort: 'high' },
      messages: [{ role: 'user', content: ctx + focus }],
    };
    const data = await claudeFetch(apiKey, body);
    usage.push(usageOf(data, 'plan · ' + m.name, PLAN_MAX_TOKENS));
    const text = ((data && data.content) || []).filter((b) => b.type === 'text').map((b) => b.text).join('');
    let parsed = {}; try { parsed = JSON.parse(text); } catch (e) {}
    return Array.isArray(parsed.issues) ? parsed.issues : [];
  };

  // No milestones → one whole-plan call (still budget-instrumented).
  if (!milestones.length) {
    noteProgress(onProgress, 'Planning the build (single pass)');
    const body = {
      model: MODEL, max_tokens: PLAN_MAX_TOKENS, system: PLAN_SYSTEM,
      output_config: { format: { type: 'json_schema', schema: obj({ plan: PLAN_PROP }, ['plan']) }, effort: 'high' },
      messages: [{ role: 'user', content: ctx }],
    };
    const data = await claudeFetch(apiKey, body);
    usage.push(usageOf(data, 'plan · (whole)', PLAN_MAX_TOKENS));
    const text = ((data && data.content) || []).filter((b) => b.type === 'text').map((b) => b.text).join('');
    let parsed = {}; try { parsed = JSON.parse(text); } catch (e) {}
    return { plan: Array.isArray(parsed.plan) ? parsed.plan : [], usage, review: null };
  }

  const plan = [];
  const priorIssues = [];   // FULL issue objects, accumulated across milestones
  for (let i = 0; i < milestones.length; i++) {
    const m = milestones[i];
    const issues = await callFor(m, priorIssues, i + 1, milestones.length);
    plan.push({ milestone: m.name, issues });
    issues.forEach((it) => { if (it && it.title) priorIssues.push(Object.assign({ milestone: m.name }, it)); });
  }

  // ── Final cohesion pass: review the WHOLE plan against the business requirements
  //    and the governance library — fill coverage gaps, drop duplicates. One call
  //    that sees everything at once (the per-milestone calls each saw a slice).
  let review = null;
  try {
    noteProgress(onProgress, 'Final cohesion review vs requirements + governance');
    const ADDITION_OBJ = obj(Object.assign({ milestone: str('The EXACT milestone name this missing issue belongs to') }, ISSUE_OBJ.properties), ['milestone'].concat(ISSUE_OBJ.required));
    const cohesionSchema = obj({
      additions: arr(ADDITION_OBJ, 'MISSING issues — any business requirement with no issue covering it, or a governance phase a milestone needs but lacks. Fully detailed, like the others. Empty array if coverage is already complete.'),
      removals: arr(obj({ milestone: str('milestone of the issue to remove'), title: str('the EXACT title of the redundant/duplicate issue to remove') }, ['milestone', 'title']), 'Issues that DUPLICATE another (same work). Remove the redundant one. Empty array if none.'),
      review: str('A short coverage summary: which requirements/phases were thin, what you added/removed and why, and your confidence the plan is complete and correct.'),
    }, ['additions', 'removals', 'review']);
    const all = plan.flatMap((g) => (g.issues || []).map((it) => Object.assign({ milestone: g.milestone }, it)));
    const cohesionFocus = '\n\n=== THE CURRENT BUILD PLAN (every issue across every milestone) ===\n' + JSON.stringify(all, null, 2) +
      '\n\n=== YOUR TASK ===\nReview the ENTIRE plan for cohesion and completeness against (a) the business requirements and (b) the governance library above. Identify and FIX: (1) any business requirement with no issue covering it; (2) any governance phase a milestone should include but is missing (requirements/architecture/design/implementation/review/testing/release); (3) cross-milestone DUPLICATES. Return `additions` (the missing issues, fully detailed, assigned to the right milestone), `removals` (redundant issues), and a `review` note. Hundreds of hours of downstream work depend on this being complete and correct — be thorough.';
    const body = {
      model: MODEL, max_tokens: PLAN_MAX_TOKENS, system: PLAN_SYSTEM,
      output_config: { format: { type: 'json_schema', schema: cohesionSchema }, effort: 'high' },
      messages: [{ role: 'user', content: ctx + cohesionFocus }],
    };
    const data = await claudeFetch(apiKey, body);
    usage.push(usageOf(data, 'cohesion review', PLAN_MAX_TOKENS));
    const text = ((data && data.content) || []).filter((b) => b.type === 'text').map((b) => b.text).join('');
    let parsed = {}; try { parsed = JSON.parse(text); } catch (e) {}
    const byMs = {}; plan.forEach((g) => { byMs[g.milestone] = g; });
    // Apply removals (exact milestone+title match).
    const rm = (parsed.removals || []).filter(Boolean);
    rm.forEach((r) => { const g = byMs[r.milestone]; if (g) g.issues = g.issues.filter((it) => it.title !== r.title); });
    // Apply additions (append to the named milestone; fall back to the first).
    const add = (parsed.additions || []).filter(Boolean);
    add.forEach((a) => {
      const g = byMs[a.milestone] || plan[0]; if (!g) return;
      const { milestone, ...issue } = a; g.issues.push(issue);
    });
    review = { note: String(parsed.review || '').trim(), added: add.length, removed: rm.length };
    noteProgress(onProgress, 'Cohesion review: +' + add.length + ' added, -' + rm.length + ' removed');
  } catch (e) { console.log('[enrich] cohesion review failed: ' + (e.message || e)); }

  return { plan, usage, review };
}

module.exports = { enrich, enrichArchitecture, enrichPlan, aiEnabled, ENRICH_SCHEMA, MODEL, GOV_LABELS };
