// ============================================================================
//  enrich.js — Stage 3 (AI): turn a plain intake into richer docs content.
//
//  One structured-output Claude call (raw fetch, no SDK) that returns:
//   - a Mermaid architecture diagram (from the locked decisions),
//   - a Mermaid Gantt (from the milestones),
//   - Given/When/Then acceptance criteria per requirement,
//   - full ADR bodies (context / trade-off / revisit) per decision.
//  render-intake injects these into the generated pages.
// ============================================================================
'use strict';

const fs = require('fs');
const path = require('path');

const API_URL = 'https://api.anthropic.com/v1/messages';
const MODEL = process.env.WIZARD_MODEL || 'claude-opus-4-8';

// Per-call OUTPUT budgets. Opus 4.8 accepts up to ~128k output tokens, so the old
// 32k was self-imposed. The docs pass and EACH per-milestone plan call get a generous
// cap so detail is never cut to fit. (Input is the 1M context — never the constraint.)
const DOCS_MAX_TOKENS = Number(process.env.DOCS_MAX_TOKENS) || 48000;
const PLAN_MAX_TOKENS = Number(process.env.PLAN_MAX_TOKENS) || 64000;

// Governance phase labels — must match lib/linear.js GOV_LABELS.
const GOV_LABELS = ['gov:owner-action', 'gov:phase-01-requirements', 'gov:phase-02-architecture', 'gov:phase-03-design', 'gov:phase-04-implementation', 'gov:phase-05-review', 'gov:phase-06-testing', 'gov:phase-07-release'];

const str = (d) => ({ type: 'string', description: d });
const obj = (p, r) => ({ type: 'object', additionalProperties: false, properties: p, required: r });
const arr = (items, d) => ({ type: 'array', description: d, items });

// The build plan is generated by its OWN focused AI call(s) (enrichPlan) — in fact
// ONE call PER MILESTONE — so each milestone's issues get the full output budget and
// detail is never cut to fit. ISSUE_OBJ is the per-issue schema, reused by both the
// per-milestone call and the whole-plan fallback.
const ISSUE_OBJ = obj({
  title: str('A concrete, narrowly-scoped Linear issue title — ONE shippable thing (a single feature, endpoint, screen, table/migration, integration, or setup task)'),
  owner: { type: 'string', enum: ['Human', 'AI'], description: 'Who does it. "Human" = work only a person can do: creating accounts/signups, minting API keys & secrets, DNS/domain/billing/payment-provider/OAuth setup, approvals, manual verification. "AI" = code/docs/tests/migrations a coding agent writes. EVERY project has several Human setup tasks — identify them; never default everything to AI.' },
  objective: str('One sentence: what this task accomplishes'),
  steps: arr(str('One concrete, self-contained step. HUMAN: a fully click-by-click action a non-technical person can follow blind — the exact site/screen, the button/menu by name, what to type, the precise value to copy and where to paste it, and how to confirm it worked. AI: a precise, imperative build instruction — the exact file(s)/module(s) to create or change, the functions/endpoints/data shapes, the approach, libraries, commands, and edge cases.'), 'The COMPLETE ordered step-by-step for THIS task — NEVER empty and never just the objective restated. Use as many steps as it genuinely needs (a small atomic task 3–6; a meatier one 6–12).'),
  notes: str('Deep execution detail beyond the steps. AI: technical approach, files/modules/functions, data shapes & schemas, libraries (+ versions), commands, how to test, gotchas/failure modes — production-quality first pass. HUMAN: prerequisites, direct links, account/permission needs, pitfalls. Markdown allowed.'),
  doneWhen: str('The acceptance check — how you know this task is complete and correct'),
  label: { type: 'string', enum: GOV_LABELS, description: 'The governance phase this task belongs to' },
}, ['title', 'owner', 'objective', 'steps', 'notes', 'doneWhen', 'label']);
const ISSUES_DESC = 'The atomic sub-issues in build order — MULTIPLE per milestone (one per discrete requirement/feature/deliverable, PLUS the phase tasks: setup, schema/migration, implementation, tests, review, release). A milestone with real scope has SEVERAL issues; never collapse it into one mega-issue.';
const PLAN_PROP = arr(obj({
  milestone: str('The EXACT intake milestone name this group of work belongs to'),
  issues: arr(ISSUE_OBJ, ISSUES_DESC),
}, ['milestone', 'issues']), 'Every intake milestone broken into atomic, governance-phased sub-issues. Cover EVERY requirement (each → one or more issues) and add the setup/architecture/review/testing/release tasks a disciplined team would, including the Human owner-action setup (accounts, keys, DNS, billing).');

const ENRICH_SCHEMA = obj({
  architecture: obj({
    layers: arr(obj({
      label: str('The layer label shown on the left edge, e.g. "User", "DNS · Cloudflare", "Edge", "Data · Auth · Payments", "Side services · Backups", "CI / CD". Order layers top→bottom: people/clients first, then edge/CDN, the application, data/auth/payments, side services, and the CI/CD pipeline last.'),
      nodes: arr(obj({
        id: str('a short unique lowercase id, e.g. "app", "postgres", "ghactions"'),
        title: str('the node title, e.g. "Traefik · app.lan" or "PostgreSQL 16 · pgvector (Docker)"'),
        eyebrow: str('a small label above the title, e.g. "Our app · Docker" or "Identity · Entra ID", or "" '),
        lines: arr(str('a plain detail line (tech/config)'), 'detail lines under the title (no bullet)'),
        bullets: arr(str('a key specific'), 'bullet specifics, shown with a • '),
        subs: arr(obj({ head: str('sub-box heading, e.g. "Middleware" or "Endpoints"'), lines: arr(str('a line'), 'lines in the sub-box') }, ['head', 'lines']), 'optional sub-boxes inside this node (e.g. the application\'s Middleware + Endpoints)'),
        cls: { type: 'string', enum: ['actor', 'edge', 'app', 'saas', 'data', 'infra'], description: 'actor=users; edge=CDN/DNS/proxy; app=OUR app/runtime; saas=third-party SaaS; data=databases/stores; infra=CI/CD/registry/deploy' },
      }, ['id', 'title', 'cls']), 'nodes in this layer, left→right'),
    }, ['label', 'nodes']), 'The ordered architectural layers, top→bottom. Technically precise (tech + version + ADR + key specifics, incl. the app\'s middleware/endpoints as subs), grounded in the locked decisions and the real codebase — but CONCISE like a clean reference diagram so each box stays compact: the people (User, Developer, Claude Code) get exactly ONE short descriptor line (e.g. "Browser · Mobile · PWA", "Builds & ships the app", "AI coding agent") and NO bullets; service nodes get at most 1–3 short lines plus at most 4 short bullets. Tight, not verbose.'),
    edges: arr(obj({
      from: str('source node id'), to: str('target node id'),
      label: str('a short edge label, e.g. "HTTPS", "verify JWT", "webhook", "deploy", or ""'),
      kind: { type: 'string', enum: ['default', 'critical', 'webhook', 'backup', 'deploy'] },
    }, ['from', 'to']), 'connections between node ids — the runtime data flows, the CI/CD pipeline chain, and the deploy edge into the application.'),
  }, ['layers']),
  architectureNote: str('1–2 sentences describing the architecture in plain language.'),
  ganttMermaid: str('A Mermaid `gantt` chart from the milestones (use each milestone name as a section/task; derive durations from targets like "Week 2"). Valid Mermaid only, no code fences.'),
  stackComponents: arr(obj({
    category: str('The role in the stack, e.g. "App host", "Database", "Auth", "Payments", "Marketing", "Email", "Errors", "Registry", "Backups", "CI/CD".'),
    component: str('The chosen product/tech, e.g. "Traefik", "PostgreSQL", "Entra ID".'),
    detail: str('A terse, technical one-liner of the key specifics, e.g. "PostgreSQL 16 + pgvector · container · volume-backed".'),
    adr: str('The matching ADR concern label to link (match an intake decision\'s concern), or "" if none.'),
  }, ['category', 'component', 'detail']), 'EVERY component of the stack as a labeled row, like a senior architect\'s "Stack components" table. Cover the locked decisions AND the supporting services the architecture implies (CDN, email, error-tracking, registry, backups, CI/CD).'),
  requestFlows: arr(obj({
    title: str('The flow name, e.g. "Sign up + first session", "Pay for a subscription", "Production deploy", "Backup + disaster recovery".'),
    status: str('A 1–3 word status tag, e.g. "live", "every merge", "planned".'),
    body: str('A precise TECHNICAL narrative of the end-to-end flow: the services touched, the real endpoints, and what happens at each step (2–4 sentences). You may use `code` for endpoints/identifiers.'),
  }, ['title', 'status', 'body']), 'The KEY request/operational flows end-to-end (sign-up, payment, billing, deploy, backup) — concrete and technical, naming the real endpoints and services.'),
  requirements: arr(obj({
    title: str('The requirement title, matched to the intake'),
    priority: { type: 'string', enum: ['Must', 'Should', 'May', "Won't"] },
    given: str('Given … (precondition)'),
    when: str('When … (the action)'),
    then: str('Then … (the observable outcome; may include " And …" lines separated by \\n)'),
  }, ['title', 'priority', 'given', 'when', 'then']), 'One Given/When/Then acceptance criterion per intake requirement, in the same order'),
  adrs: arr(obj({
    concern: str('The decision concern, matched to the intake'),
    choice: str('The decision'),
    context: str('Why this decision needed making (the forces)'),
    tradeoff: str('The trade-off accepted by choosing it'),
    revisit: str('The trigger that would make us revisit this decision'),
  }, ['concern', 'choice', 'context', 'tradeoff', 'revisit']), 'One ADR body per intake decision, in the same order'),
}, ['architecture', 'architectureNote', 'ganttMermaid', 'stackComponents', 'requestFlows', 'requirements', 'adrs']);

const SYSTEM =
  'You expand a software project plan into richer documentation and a governance-phased build runbook. You are given the project intake (product, requirements, decisions, milestones) and, when available, excerpts of the existing/related codebase. Produce: a DETAILED, reference-quality architecture as structured LAYER DATA (the `architecture` field — ordered top→bottom layers of detailed nodes, plus edges), grounded in the locked decisions and the real codebase. The TOP "User" lane holds the end User AND the Developer + Claude Code (the AI coding agent); lower lanes are the category layers (Edge, Application, Data·Auth·Payments, Side services, CI/CD). Draw the dev pipeline as edges — Developer → Claude Code → GitHub → registry → deploy → the app — alongside the runtime data flows. Nodes carry tech + version + ADR + bullet specifics (the application also gets middleware/endpoints sub-boxes), exactly as the architecture field describes; a "Stack components" list covering every component (decisions + supporting services); the KEY request/operational flows end-to-end (sign-up, payment, billing, deploy, backup) as concrete technical narratives; a Mermaid Gantt from the milestones; one Given/When/Then acceptance criterion per requirement (concrete and observable — an actor and an outcome, never implementation detail); and a full ADR body per decision (context, trade-off accepted, revisit trigger). (The build plan / Linear issues are produced by a separate call — do not output a plan here.)\n\n' +
  'Be detailed and faithful to the intake and the code; do not invent scope. Output Mermaid as raw diagram source with NO code fences and NO surrounding markdown.';

function buildUserContent(intake, corpus) {
  const slim = {
    product: intake.product || {},
    requirements: (intake.requirements || []).map((r) => ({ title: r.title, priority: r.priority, test: r.test })),
    decisions: (intake.decisions || []).map((d) => ({ concern: d.concern, choice: d.choice, why: d.why })),
    milestones: (intake.milestones || []).map((m) => ({ name: m.name, done: m.done, target: m.target })),
    scalability: intake.scalability || [],
  };
  let out = 'Project intake:\n\n' + JSON.stringify(slim, null, 2) +
    '\n\nProduce the enrichment. Keep requirements and adrs in the SAME ORDER and titled the same as the intake. In `plan`, use the EXACT milestone names from the intake.';
  if (corpus && corpus.text) {
    out += '\n\n--- EXISTING CODE (' + corpus.includedCount + ' of ' + corpus.fileCount + ' uploaded files' + (corpus.truncated ? ', truncated' : '') + ') — use it to ground the diagram, decisions, and tasks ---\n' + corpus.text;
  }
  return out;
}

function aiEnabled() { return !!process.env.ANTHROPIC_API_KEY; }

// POST to the Claude API with retry-with-backoff on TRANSIENT failures (rate
// limits + Anthropic-side overload/5xx + network blips). 503/529 = overloaded,
// common for large Opus requests, and almost always succeeds on a retry. Honors a
// Retry-After header when present; otherwise exponential backoff with jitter.
// Throws (with .status) on non-retryable errors or once retries are exhausted.
const TRANSIENT_STATUS = new Set([429, 500, 502, 503, 529]);
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
const backoffMs = (attempt) => Math.min(30000, 1500 * Math.pow(2, attempt)) + Math.floor(Math.random() * 600);
async function claudeFetch(apiKey, body) {
  const MAX = Number(process.env.ENRICH_RETRIES) || 4;
  const TIMEOUT = Number(process.env.ENRICH_TIMEOUT_MS) || 600000;
  let lastErr = null;
  for (let attempt = 0; attempt <= MAX; attempt++) {
    const ctrl = new AbortController();
    const timer = setTimeout(() => ctrl.abort(), TIMEOUT);
    let res;
    try {
      res = await fetch(API_URL, {
        method: 'POST',
        headers: { 'x-api-key': apiKey, 'anthropic-version': '2023-06-01', 'content-type': 'application/json' },
        body: JSON.stringify(body), signal: ctrl.signal,
      });
    } catch (e) {
      clearTimeout(timer);
      if (e.name === 'AbortError') { const err = new Error('the AI build timed out'); err.status = 504; throw err; }
      lastErr = new Error('could not reach the Claude API: ' + e.message); lastErr.status = 503;
      if (attempt < MAX) { await sleep(backoffMs(attempt)); continue; }
      throw lastErr;
    }
    if (res.ok) { const d = await res.json().catch(() => null); clearTimeout(timer); return d; }
    const retryAfter = Number(res.headers.get('retry-after'));
    clearTimeout(timer);
    if (TRANSIENT_STATUS.has(res.status) && attempt < MAX) {
      lastErr = new Error('Claude API HTTP ' + res.status + ' (transient)');
      await sleep(retryAfter > 0 ? retryAfter * 1000 : backoffMs(attempt));
      continue;
    }
    const data = await res.json().catch(() => null);
    const err = new Error((data && data.error && data.error.message) || ('Claude API HTTP ' + res.status)); err.status = res.status; throw err;
  }
  throw lastErr || new Error('Claude API request failed');
}

async function enrich(intake, apiKey, index, onProgress, checkCancel) {
  apiKey = (apiKey && String(apiKey).trim()) || process.env.ANTHROPIC_API_KEY;
  if (!apiKey) { const e = new Error('no Claude API key provided'); e.code = 'no_key'; throw e; }
  emit(onProgress, { t: 'start', label: 'Docs — architecture, requirements & ADRs', agent: true });

  // Agentic: the model reads package.json, the schema, server routes, and config to
  // ground the architecture in reality, then submits the enrichment.
  const submit = { name: 'submit_docs', description: 'Submit the enrichment (architecture layer-data, stack components, request flows, requirement acceptance criteria, ADR bodies) exactly per the field descriptions.', input_schema: ENRICH_SCHEMA };
  const messages = [{ role: 'user', content: intakeBrief(intake) + manifestBlock(index) +
    '\n\n=== YOUR TASK ===\nExplore the codebase (start with package.json, the schema, server routes, and config) so the architecture reflects the REAL stack and structure, then call submit_docs with the enrichment per the schema. The locked decisions in the intake are the source of truth where they differ from the code.' }];
  const r = await runAgent(apiKey, { system: SYSTEM, messages: messages, tools: EXPLORE_TOOLS.concat([submit]), exec: makeExec(index), submitName: 'submit_docs', maxTokens: DOCS_MAX_TOKENS, onProgress: onProgress, label: 'Docs agent', checkCancel: checkCancel });
  emit(onProgress, { t: 'done', label: 'Docs — architecture, requirements & ADRs', tokens: { fresh: r.usage.input, cached: r.usage.cacheRead, output: r.usage.output } });
  if (!r.result) { const err = new Error('the docs pass did not produce output'); err.status = 502; throw err; }
  // The architecture diagram is structured DATA (layers + edges) rendered by a
  // deterministic swim-lane renderer, so no layout-refinement pass is needed.
  return sanitize(r.result);
}

// The design rules the diagram must satisfy — shared by the generator prompt and
// the refinement pass below.
const ARCH_RULES =
  'A DETAILED, reference-quality Mermaid `flowchart TB` drawn as stacked LAYERS, top → bottom. ' +
  '(1) Top row = the people: a "User" node (end user) and a "Developer" node, plain nodes side by side, NOT wrapped in a subgraph box. ' +
  '(2) One `subgraph` per layer, each with `direction LR` — typically "Edge" (DNS · CDN · marketing), "Application", "Data · Auth · Payments", "Side services" (email · errors · backups, if used), and "CI / CD". ' +
  '(3) Node labels are DETAILED and technically precise via <br/>: name; concrete tech + version; the relevant ADR; then 2–4 "• " bullet lines of key specifics. Do NOT dumb it down — engineers read this. The "Application" node also surfaces its key middleware and main endpoints as bullets. ' +
  '(4) Show the dev/CI pipeline as a chain: Developer → Claude Code → GitHub (repo + Actions) → container registry → deploy (flyctl rolling release) → the Application, with labeled edges. ' +
  '(5) Show the runtime path: User → Edge → Application → Data·Auth·Payments, with protocol-labeled edges (HTTPS · JWT verify · SQL · webhook). ' +
  '(6) Every node gets exactly one style class via `class <id> <class>` from: actor (User, Developer), edge, app, saas (incl. Claude Code), data, infra (GitHub/CI/registry/deploy). ' +
  '(7) Information-rich but balanced and uncrossed. No `classDef`/`style` lines. Valid Mermaid only — no code fences, no prose.';

const REFINE_SYSTEM =
  'You are a senior software architect and information designer. You refine Mermaid architecture diagrams for LAYOUT, BALANCE, GROUPING, and CLARITY without changing their technical accuracy. You output only valid Mermaid — no code fences, no commentary.';

const REFINE_SCHEMA = { type: 'object', additionalProperties: false, required: ['mermaid'],
  properties: { mermaid: { type: 'string', description: 'The refined Mermaid flowchart source — no code fences.' } } };

// Focused Opus pass that polishes the diagram's design. Any failure returns the
// original diagram unchanged, so the build never regresses on this.
async function refineArch(mmd, intake, apiKey) {
  apiKey = (apiKey && String(apiKey).trim()) || process.env.ANTHROPIC_API_KEY;
  mmd = String(mmd || '').trim();
  if (!apiKey || !mmd) return mmd;
  const prod = (intake && intake.product) || {};
  const userMsg = 'Refine this architecture diagram for ' + (prod.name || 'the product') +
    ' so it is clean, compact, balanced, and well-designed. Keep it technically faithful — improve grouping, layer ordering, spacing/balance, label wording, and reduce crossing edges. Make sure it satisfies EVERY rule.\n\n' +
    ARCH_RULES + '\n\nCURRENT DIAGRAM:\n' + mmd + '\n\nReturn ONLY the improved Mermaid in the `mermaid` field.';
  const body = {
    model: MODEL, max_tokens: 6000, system: REFINE_SYSTEM,
    output_config: { format: { type: 'json_schema', schema: REFINE_SCHEMA }, effort: 'high' },
    messages: [{ role: 'user', content: userMsg }],
  };
  const ctrl = new AbortController();
  const timer = setTimeout(() => ctrl.abort(), Number(process.env.ENRICH_TIMEOUT_MS) || 600000);
  try {
    const res = await fetch(API_URL, { method: 'POST', headers: { 'x-api-key': apiKey, 'anthropic-version': '2023-06-01', 'content-type': 'application/json' }, body: JSON.stringify(body), signal: ctrl.signal });
    const data = await res.json().catch(() => null);
    if (!res.ok) return mmd;
    const text = ((data && data.content) || []).filter((b) => b.type === 'text').map((b) => b.text).join('');
    let parsed; try { parsed = JSON.parse(text); } catch (e) { return mmd; }
    const refined = fence(parsed && parsed.mermaid);
    return (refined && /flowchart/i.test(refined)) ? refined : mmd;   // sanity-gate
  } catch (e) { return mmd; }
  finally { clearTimeout(timer); }
}

// Strip stray code fences the model sometimes wraps Mermaid in, and clamp shapes.
function fence(s) {
  return String(s || '').replace(/^\s*```[a-z]*\s*/i, '').replace(/```\s*$/i, '').trim();
}
function sanitize(p) {
  p = p || {};
  return {
    architectureMermaid: fence(p.architectureMermaid),
    architecture: (p.architecture && Array.isArray(p.architecture.layers)) ? { layers: p.architecture.layers, edges: Array.isArray(p.architecture.edges) ? p.architecture.edges : [] } : { layers: [], edges: [] },
    architectureNote: String(p.architectureNote || '').trim(),
    stackComponents: Array.isArray(p.stackComponents) ? p.stackComponents : [],
    requestFlows: Array.isArray(p.requestFlows) ? p.requestFlows : [],
    ganttMermaid: fence(p.ganttMermaid),
    requirements: Array.isArray(p.requirements) ? p.requirements : [],
    adrs: Array.isArray(p.adrs) ? p.adrs : [],
    plan: Array.isArray(p.plan) ? p.plan : [],
  };
}

// Focused, faster pass: regenerate ONLY the architecture (layers + edges + note).
// Used by the deployed editor's Assess so changing a decision (e.g. the database)
// also updates the diagram — not just the text — for review before committing.
async function enrichArchitecture(intake, apiKey, corpus) {
  apiKey = (apiKey && String(apiKey).trim()) || process.env.ANTHROPIC_API_KEY;
  if (!apiKey) return null;
  const schema = obj({ architecture: ENRICH_SCHEMA.properties.architecture, architectureNote: ENRICH_SCHEMA.properties.architectureNote }, ['architecture', 'architectureNote']);
  const archSystem = 'You are a senior software architect. Produce ONLY the system architecture as structured layer data (the `architecture` field) plus a one-line note, exactly per the field descriptions. The CURRENT locked decisions are the SOURCE OF TRUTH — if a decision was just changed (e.g. the database swapped from Postgres to Oracle), the diagram MUST reflect the NEW choice and its implications, even if the existing code in the corpus still references the old one. Be technically precise and CONCISE like a clean reference diagram (the people get one line, no bullets). The top "User" lane holds the end User + Developer + Claude Code; lower lanes are the category layers; draw the dev pipeline + runtime flows as edges.';
  const content = await fitCorpus(corpus, archSystem, function (c) { return buildUserContent(intake, c); }, apiKey, 'architecture');
  const body = {
    model: MODEL, max_tokens: 8000,
    system: archSystem,
    output_config: { format: { type: 'json_schema', schema: schema }, effort: 'high' },
    messages: [{ role: 'user', content: content }],
  };
  const data = await claudeFetch(apiKey, body);
  const text = ((data && data.content) || []).filter((b) => b.type === 'text').map((b) => b.text).join('');
  const parsed = JSON.parse(text);
  if (!parsed || !parsed.architecture || !Array.isArray(parsed.architecture.layers)) return null;
  return { architecture: { layers: parsed.architecture.layers, edges: Array.isArray(parsed.architecture.edges) ? parsed.architecture.edges : [] }, architectureNote: String(parsed.architectureNote || '').trim() };
}

// Dedicated build-plan pass — its OWN full output budget, so the issues come out
// granular (many atomic sub-issues per milestone), properly owner-split, and fully
// step-by-step instead of starving at the tail of the big docs enrichment.
const PLAN_SYSTEM =
  'You are a senior tech lead turning a project intake into a COMPLETE, governance-phased build backlog of Linear issues. You are given the product, requirements, locked decisions, milestones, and (when available) the codebase.\n\n' +
  'Produce ONLY the `plan`: every intake milestone broken into ATOMIC sub-issues. Be GRANULAR — one issue per discrete deliverable (a single feature, endpoint, screen, table/migration, integration, or setup task), NOT one big issue per milestone. Cover EVERY requirement (each maps to one or more issues) and add the phase tasks a disciplined team always has: project/repo setup, schema & migrations, each feature, tests, review, release. A real milestone has SEVERAL issues — usually 4–10.\n\n' +
  'The locked DECISIONS define the TARGET stack — they are the SOURCE OF TRUTH for infrastructure, NOT the services the uploaded code happens to use today. If the app currently runs on different infra (a hosted prototype, a different DB, a vendor auth), that infra does NOT carry over — MIGRATING to the target stack is real, planned work. Read the existing code to understand WHAT the app does and HOW it is wired, then plan what it takes to deliver that on the LOCKED stack. Never label a migration as if the old service transfers (e.g., if the decision is Microsoft Entra / Azure AD, do not write "use the existing vendor OAuth").\n\n' +
  'Split owners correctly, and DO NOT under-count Human work. Mark as HUMAN every task only a person can do — creating accounts/signups, minting API keys & secrets, registering OAuth/identity apps, DNS/domain/TLS-cert setup, billing, approvals, and manual verification. CRITICAL: for EVERY external account, credential, third-party API, identity provider, and on-prem infrastructure piece the TARGET stack requires — databases/servers, file servers, OAuth/identity apps, mapping/LLM/payment APIs, DNS, TLS certs, service accounts — emit a HUMAN owner-action issue to PROVISION it. Do not assume an existing service transfers and do not fold five provisioning steps into one issue. An on-prem / self-hosted port typically needs 6–12 Human issues, not 2–3. Mark as AI the code/docs/tests/migrations a coding agent writes; do NOT default everything to AI.\n\n' +
  'Keep every issue in service of the MASTER GOAL (stated at the top of the intake) — that is WHY the requirements exist; reject scope that does not advance it.\n\n' +
  'Make EACH issue a complete, self-contained runbook entry — NEVER just an objective. Give: a one-sentence objective; the FULL ordered steps (HUMAN → click-by-click a non-technical person can follow blind; AI → a mini-spec naming the exact files/modules/functions, data shapes, libraries, commands, tests, and edge cases); deep execution notes; a done-when acceptance check; and the single best governance label. An issue with empty steps is unacceptable.\n\n' +
  'Be faithful to the intake and the code; do not invent scope. The issue is kicked off by a human telling Claude `start <issue-id>`, so steps must be directly actionable.';

function usageOf(data, label, max) {
  const u = (data && data.usage) || {};
  const rec = { pass: label, input: u.input_tokens || 0, output: u.output_tokens || 0, max: max, stop: (data && data.stop_reason) || null };
  rec.truncated = rec.stop === 'max_tokens';   // hit the output cap → detail WAS cut
  rec.headroomPct = max ? Math.round((1 - rec.output / max) * 100) : null;
  console.log('[enrich] ' + label + ': in=' + rec.input + ' out=' + rec.output + '/' + max +
    ' (' + rec.headroomPct + '% headroom) stop=' + rec.stop + (rec.truncated ? '  ⚠️ TRUNCATED' : ''));
  return rec;
}

// The project-agnostic 7-phase governance LIBRARY (the development process every
// issue must fit) lives as HTML in docs-kit.js. Strip it to text ONCE and feed the
// FULL library into every plan + cohesion call — grounding issues in the process.
let _govText = null;
function governanceText() {
  if (_govText !== null) return _govText;
  try {
    const src = fs.readFileSync(path.join(__dirname, 'docs-kit.js'), 'utf8');
    const entries = src.match(/"governance\/library\/0[0-7][^"]*":\s*"((?:[^"\\]|\\.)*)"/g) || [];
    _govText = entries.map((s) => {
      let html = '';
      try { html = JSON.parse(s.slice(s.indexOf(':') + 1).trim()); } catch (e) { return ''; }
      return html
        .replace(/<style[\s\S]*?<\/style>/gi, ' ').replace(/<script[\s\S]*?<\/script>/gi, ' ')
        .replace(/<\/(p|h[1-6]|li|tr|section|div)>/gi, '\n').replace(/<li[^>]*>/gi, '\n• ')
        .replace(/<[^>]+>/g, ' ').replace(/&[a-z]+;/gi, ' ')
        .replace(/[ \t]+/g, ' ').replace(/\n[ \t]*\n[ \t]*\n+/g, '\n\n').trim();
    }).filter(Boolean).join('\n\n———\n\n');
  } catch (e) { _govText = ''; }
  return _govText;
}

// The full reference context fed to EVERY plan + cohesion call: the whole intake
// (product, ALL requirements/decisions/milestones), the whole uploaded codebase, and
// the FULL governance library. Quality-over-speed: we deliberately fill the 1M input
// window so the model has everything it needs to be right the first time.
function planContext(intake, corpus) {
  let c = buildUserContent(intake, corpus);
  const gov = governanceText();
  if (gov) c += '\n\n=== GOVERNANCE LIBRARY — the 7-phase development process EVERY issue must fit. Label each issue with the correct gov:phase, and make sure each milestone honors the phases (requirements → architecture → design → implementation → review → testing → release) ===\n' + gov;
  return c;
}

function noteProgress(onProgress, msg) { console.log('[enrich] ▶ ' + msg); if (typeof onProgress === 'function') { try { onProgress({ t: 'start', label: msg }); } catch (e) {} } }

// Cooperative cancel: the build checks this between agent steps and aborts cleanly
// (nothing is written to Linear/docs until the very end, so an abort persists nothing).
function bail(checkCancel) { if (typeof checkCancel === 'function' && checkCancel()) { const e = new Error('build cancelled'); e.cancelled = true; throw e; } }

// Structured progress events so the GUI can show the exact phase, a live "agent
// running" indicator, and per-phase token counts. ev: { t:'start'|'activity'|'done',
// label, detail, tokens:{fresh,cached,output}, note, agent:bool }.
function emit(onProgress, ev) {
  const k = ev.tokens ? ' [' + Math.round((ev.tokens.fresh || 0) / 1000) + 'K fresh +' + Math.round((ev.tokens.cached || 0) / 1000) + 'K cached → ' + Math.round((ev.tokens.output || 0) / 1000) + 'K out]' : '';
  console.log('[enrich] ' + (ev.t === 'start' ? '▶ ' : ev.t === 'done' ? '✓ ' : '  · ') + (ev.label || ev.detail || '') + k + (ev.note ? ' (' + ev.note + ')' : ''));
  if (typeof onProgress === 'function') { try { onProgress(ev); } catch (e) {} }
}
// Human phrase for what the agent just did (read/search/list/write).
function describeTools(tus) {
  return tus.map((t) => {
    if (t.name === 'read_file') return 'reading ' + String(t.input && t.input.path || '').split('/').pop();
    if (t.name === 'search_code') return 'searching “' + String(t.input && t.input.pattern || '') + '”';
    if (t.name === 'list_files') return 'listing files';
    if (String(t.name).indexOf('submit') === 0) return 'writing result';
    return t.name;
  }).join(', ');
}

// The model's hard INPUT cap is 1M tokens. We want to fill it — but never exceed it.
// Leave headroom for the output budget + the JSON-schema overhead (not counted below).
const INPUT_CEILING = Number(process.env.WIZARD_INPUT_CEILING) || 900000;

// Ask the API exactly how many input tokens a prompt is (no guessing across code
// densities). Falls back to a conservative chars/2.5 estimate if the endpoint fails.
async function countTokens(apiKey, system, content) {
  try {
    const res = await fetch(API_URL + '/count_tokens', {
      method: 'POST',
      headers: { 'x-api-key': apiKey, 'anthropic-version': '2023-06-01', 'content-type': 'application/json' },
      body: JSON.stringify({ model: MODEL, system: system, messages: [{ role: 'user', content: content }] }),
    });
    if (!res.ok) return Math.ceil(content.length / 2.5);
    const j = await res.json();
    return (j && j.input_tokens) || Math.ceil(content.length / 2.5);
  } catch (e) { return Math.ceil(content.length / 2.5); }
}

// Build the prompt and, if it exceeds INPUT_CEILING, trim ONLY the (large, trimmable)
// CORPUS — buildFn rebuilds the prompt from a trimmed corpus, so everything else the
// caller composes (intake, governance, the task/prior-issue tail) stays FULLY intact.
// The ONLY thing ever shortened is the uploaded reference corpus. Maximizes input use
// without overflowing 1M.
async function fitCorpus(corpus, system, buildFn, apiKey, label) {
  let budget = (corpus && corpus.text) ? corpus.text.length : 0;
  let content = buildFn(corpus);
  for (let i = 0; i < 7; i++) {
    const tokens = await countTokens(apiKey, system, content);
    if (tokens <= INPUT_CEILING || budget <= 0) {
      if (i > 0) console.log('[enrich] ' + (label || 'call') + ': trimmed reference corpus to fit — ~' + tokens + ' input tokens');
      return content;
    }
    // Proportional trim: scale the corpus by how far over we are. Only the corpus
    // shrinks (the intake/governance/tail stay fixed), so this lands just UNDER the
    // ceiling in one or two steps while keeping as much codebase as will fit.
    budget = Math.max(0, Math.floor(budget * (INPUT_CEILING / tokens) * 0.97));
    const trimmed = Object.assign({}, corpus, { text: corpus.text.slice(0, budget) + '\n…[uploaded reference corpus trimmed to fit the 1M context window — the wizard intake + governance are kept in full]' });
    content = buildFn(trimmed);
  }
  return content;
}

// Plan/docs/cohesion content = full intake + governance + (trimmed) corpus + tail.
async function fittedContent(intake, corpus, system, tail, apiKey, label) {
  tail = tail || '';
  return fitCorpus(corpus, system, function (c) { return planContext(intake, c) + tail; }, apiKey, label);
}

// Generate the build plan ONE MILESTONE AT A TIME so each milestone's issues get the
// full PLAN_MAX_TOKENS output budget — detail is never cut to share a budget. Returns
// { plan, usage } where usage has a per-call token record (so we can prove no pass
// hit the cap). If a milestone ever does truncate, raise PLAN_MAX_TOKENS or it gets
// auto-flagged in usage.
// ── Agentic enrichment: the model gets TOOLS to explore the upload on demand instead
//    of prefilling the whole codebase. ~100× cheaper (reads only relevant files) and
//    more accurate (grounds each issue in code it actually pulled).
const EXPLORE_TOOLS = [
  { name: 'list_files', description: 'List the uploaded codebase files (path + size), importance-ranked. Optional "glob": a path substring to filter (e.g. "server/", ".tsx", "schema").', input_schema: { type: 'object', properties: { glob: { type: 'string', description: 'optional path substring filter' } } } },
  { name: 'read_file', description: 'Read the full text of ONE uploaded file by its exact path from the manifest.', input_schema: { type: 'object', properties: { path: { type: 'string' } }, required: ['path'] } },
  { name: 'search_code', description: 'Case-insensitive regex/substring search across the whole upload; returns file:line matches. Use it to find where things are defined or used.', input_schema: { type: 'object', properties: { pattern: { type: 'string' }, max: { type: 'number', description: 'max matches (default 50)' } }, required: ['pattern'] } },
];
function makeExec(index) {
  return async (name, input) => {
    input = input || {};
    if (!index) return '(no codebase was uploaded for this project)';
    if (name === 'list_files') return index.list(input.glob);
    if (name === 'read_file') return index.read(input.path);
    if (name === 'search_code') return index.search(input.pattern, input.max);
    return 'unknown tool: ' + name;
  };
}
function intakeBrief(intake) {
  const slim = {
    product: intake.product || {}, startDate: intake.startDate || '',
    requirements: (intake.requirements || []).map((r) => ({ title: r.title, priority: r.priority, test: r.test })),
    decisions: (intake.decisions || []).map((d) => ({ concern: d.concern, choice: d.choice, why: d.why })),
    milestones: (intake.milestones || []).map((m) => ({ name: m.name, done: m.done, target: m.target })),
    scalability: intake.scalability || [],
  };
  const goal = String((intake.product && intake.product.goal) || '').trim();
  const goalBlock = goal ? '★ MASTER GOAL OF THIS PROJECT (the north star — every issue must serve it; this is WHY the requirements exist. Reject scope that does not advance it, and keep the plan tightly focused on reaching it):\n' + goal + '\n\n' : '';
  return goalBlock + 'PROJECT INTAKE (source of truth — requirements, decisions, milestones):\n' + JSON.stringify(slim, null, 2);
}
function manifestBlock(index) {
  return index && index.fileCount
    ? '\n\n=== UPLOADED CODEBASE (' + index.fileCount + ' files) — explore with list_files / read_file / search_code. READ the real models, routes, components, config before writing issues; never guess. ===\n' + index.manifest()
    : '\n\n(No codebase uploaded — plan from the intake + governance.)';
}

const COMPACT_THRESHOLD = Number(process.env.WIZARD_COMPACT_TOKENS) || 700000;
const PLAN_SYSTEM_AGENT = PLAN_SYSTEM +
  '\n\nYou have TOOLS to explore the uploaded codebase: list_files, read_file, search_code. USE them — read the actual schema, routes, components, and config so every issue is grounded in the real code, not guesses. Be efficient: read what a milestone needs, not the whole repo. When a milestone is fully covered, call submit_milestone; you will then be asked for the next. Reuse what you already read across milestones.';

// Prompt-CACHED agentic call. A continuous tool-using session re-sends its whole
// growing context every step; caching the system + tools + conversation prefix means
// that prefix is re-read at ~10% cost instead of re-billed in full — this is what makes
// going agentic actually cheap. Marks a single moving breakpoint at the last block.
async function agentFetch(apiKey, system, tools, messages, maxTokens, toolChoice) {
  const sys = [{ type: 'text', text: system, cache_control: { type: 'ephemeral' } }];
  const tls = (tools || []).map((t, i) => (i === tools.length - 1 ? Object.assign({}, t, { cache_control: { type: 'ephemeral' } }) : t));
  for (const m of messages) if (Array.isArray(m.content)) for (const b of m.content) { if (b && b.cache_control) delete b.cache_control; }
  const last = messages[messages.length - 1];
  if (last) {
    if (typeof last.content === 'string') last.content = [{ type: 'text', text: last.content }];
    if (Array.isArray(last.content) && last.content.length) { const lc = last.content[last.content.length - 1]; if (lc && typeof lc === 'object') lc.cache_control = { type: 'ephemeral' }; }
  }
  const body = { model: MODEL, max_tokens: maxTokens, system: sys, tools: tls, tool_choice: toolChoice || { type: 'auto' }, messages: messages };
  return claudeFetch(apiKey, body);
}
function cacheTok(data) { const u = (data && data.usage) || {}; return { read: u.cache_read_input_tokens || 0, write: u.cache_creation_input_tokens || 0, fresh: u.input_tokens || 0 }; }

// Generic single-submit agent loop: explore via tools (executed by `exec`), finish by
// calling `submitName` (a structured-output tool). Returns { result, usage }.
async function runAgent(apiKey, opts) {
  const { system, messages, tools, exec, submitName, maxSteps, maxTokens, onProgress, label, checkCancel } = opts;
  let inTok = 0, outTok = 0, cacheRd = 0;
  for (let step = 0; step < (maxSteps || 60); step++) {
    bail(checkCancel);
    const data = await agentFetch(apiKey, system, tools, messages, maxTokens || 32000);
    const ct = cacheTok(data); inTok += ct.fresh + ct.write; outTok += (data && data.usage && data.usage.output_tokens) || 0; cacheRd += ct.read;
    const blocks = (data && data.content) || [];
    messages.push({ role: 'assistant', content: blocks });
    const tus = blocks.filter((b) => b.type === 'tool_use');
    if (tus.length) emit(onProgress, { t: 'activity', detail: (label ? label + ': ' : '') + describeTools(tus), tokens: { fresh: inTok, cached: cacheRd, output: outTok }, agent: true });
    if (!tus.length) { messages.push({ role: 'user', content: 'Call ' + submitName + ' now with your result.' }); continue; }
    const sub = tus.find((t) => t.name === submitName);
    const rb = [];
    for (const t of tus) {
      if (t.name === submitName) continue;
      let out; try { out = await exec(t.name, t.input); } catch (e) { out = 'error: ' + (e.message || e); }
      rb.push({ type: 'tool_result', tool_use_id: t.id, content: String(out).slice(0, 80000) });
    }
    if (sub) return { result: sub.input, usage: { input: inTok, output: outTok, cacheRead: cacheRd } };
    messages.push({ role: 'user', content: rb });
  }
  return { result: null, usage: { input: inTok, output: outTok, cacheRead: cacheRd } };
}

// Dense handoff notes so a fresh session continues without re-reading — used only when
// the conversation nears the context limit.
async function compactKnowledge(apiKey, messages, tools, usage) {
  const m = messages.concat([{ role: 'user', content: 'CONTEXT IS NEARLY FULL — you will continue in a FRESH session. Write dense technical HANDOFF NOTES (prose, no tool calls) of everything you learned about this codebase relevant to the REMAINING milestones: architecture, key modules/files WITH PATHS, the data model (tables/fields/relations), API/route patterns, conventions, integrations, gotchas. Be specific enough to not need to re-read these files.' }]);
  const data = await agentFetch(apiKey, 'Summarize your codebase knowledge densely for your own fresh planning session.', tools, m, 12000, { type: 'none' });
  const ct = cacheTok(data); usage.push({ pass: 'compact', input: ct.fresh + ct.write, cacheRead: ct.read, output: (data && data.usage && data.usage.output_tokens) || 0, max: 12000 });
  return ((data && data.content) || []).filter((b) => b.type === 'text').map((b) => b.text).join('').trim();
}

// Agentic cohesion review against requirements + governance (reads code to verify).
async function cohesionReview(apiKey, intake, index, gov, results, usage, onProgress, checkCancel) {
  emit(onProgress, { t: 'start', label: 'Cohesion review — Review agent running (vs requirements + governance)', agent: true });
  const ADDITION_OBJ = obj(Object.assign({ milestone: str('The EXACT milestone name this missing issue belongs to') }, ISSUE_OBJ.properties), ['milestone'].concat(ISSUE_OBJ.required));
  const submit = { name: 'submit_review', description: 'Submit the cohesion review.', input_schema: obj({
    additions: arr(ADDITION_OBJ, 'MISSING issues — any requirement with no covering issue, or a governance phase a milestone lacks. Fully detailed. Empty array if complete.'),
    removals: arr(obj({ milestone: str('milestone of the issue to remove'), title: str('EXACT title of the redundant issue to remove') }, ['milestone', 'title']), 'Duplicate/redundant issues to remove. Empty array if none.'),
    review: str('Short coverage summary: thin spots, what you added/removed and why, confidence.'),
  }, ['additions', 'removals', 'review']) };
  const all = results.flatMap((g) => (g.issues || []).map((it) => Object.assign({ milestone: g.milestone }, it)));
  const messages = [{ role: 'user', content: intakeBrief(intake) + '\n\n=== GOVERNANCE LIBRARY ===\n' + gov + manifestBlock(index) +
    '\n\n=== THE CURRENT BUILD PLAN (every issue) ===\n' + JSON.stringify(all, null, 2) +
    '\n\n=== YOUR TASK ===\nReview the ENTIRE plan for cohesion + completeness vs (a) the business requirements, (b) the governance library, and (c) the MASTER GOAL. You may read the code to verify. Find & FIX: (1) any requirement with no covering issue; (2) any governance phase a milestone should have but lacks; (3) cross-milestone duplicates; (4) HUMAN-SETUP COVERAGE — go through the locked DECISIONS and confirm that EVERY external account, credential, API key, identity/OAuth app, third-party API, and on-prem infrastructure piece the TARGET stack requires (database/server + service account, file server, Entra/Azure AD or other identity app, mapping/LLM/payment keys, DNS, TLS certs) has a HUMAN owner-action issue to provision it — add the missing ones (a self-hosted/on-prem port usually needs 6–12 Human issues); and fix any issue that wrongly assumes an existing prototype service carries over instead of being migrated to the locked stack. Then call submit_review.' }];
  const r = await runAgent(apiKey, { system: PLAN_SYSTEM_AGENT, messages: messages, tools: EXPLORE_TOOLS.concat([submit]), exec: makeExec(index), submitName: 'submit_review', maxTokens: PLAN_MAX_TOKENS, onProgress: onProgress, label: 'Review agent', checkCancel: checkCancel });
  usage.push({ pass: 'cohesion', input: r.usage.input, cacheRead: r.usage.cacheRead, output: r.usage.output, max: PLAN_MAX_TOKENS });
  const parsed = r.result || {};
  const byMs = {}; results.forEach((g) => { byMs[g.milestone] = g; });
  const rm = (parsed.removals || []).filter(Boolean);
  rm.forEach((rr) => { const g = byMs[rr.milestone]; if (g) g.issues = g.issues.filter((it) => it.title !== rr.title); });
  const add = (parsed.additions || []).filter(Boolean);
  add.forEach((a) => { const g = byMs[a.milestone] || results[0]; if (!g) return; const { milestone, ...issue } = a; g.issues.push(issue); });
  emit(onProgress, { t: 'done', label: 'Cohesion review', tokens: { fresh: r.usage.input, cached: r.usage.cacheRead, output: r.usage.output }, note: '+' + add.length + ' / -' + rm.length });
  return { note: String(parsed.review || '').trim(), added: add.length, removed: rm.length };
}

// Plan the build as Linear issues by EXPLORING the codebase on demand — one milestone
// at a time in a continuous session (reads + prior issues accumulate), compacting to
// handoff notes only when the context nears the limit, then a cohesion review.
async function enrichPlan(intake, apiKey, index, onProgress, checkCancel) {
  apiKey = (apiKey && String(apiKey).trim()) || process.env.ANTHROPIC_API_KEY;
  if (!apiKey) return { plan: [], usage: [], review: null };
  const milestones = (intake.milestones || []).filter((m) => m && (m.name || m.done));
  const gov = governanceText();
  const usage = [];
  const exec = makeExec(index);
  const govBlock = '\n\n=== GOVERNANCE LIBRARY (every issue must fit the 7-phase process; label each with the correct gov:phase) ===\n' + gov;

  // No milestones → single agentic whole-plan call.
  if (!milestones.length) {
    const whole = { name: 'submit_plan', description: 'Submit the whole build plan: milestones, each with atomic sub-issues.', input_schema: obj({ plan: PLAN_PROP }, ['plan']) };
    const messages = [{ role: 'user', content: intakeBrief(intake) + govBlock + manifestBlock(index) + '\n\n=== YOUR TASK ===\nExplore the code, then call submit_plan with the full milestone→issues plan.' }];
    const r = await runAgent(apiKey, { system: PLAN_SYSTEM_AGENT, messages: messages, tools: EXPLORE_TOOLS.concat([whole]), exec: exec, submitName: 'submit_plan', maxTokens: PLAN_MAX_TOKENS, onProgress: onProgress, checkCancel: checkCancel });
    usage.push({ pass: 'plan (whole)', input: r.usage.input, output: r.usage.output, max: PLAN_MAX_TOKENS });
    return { plan: (r.result && Array.isArray(r.result.plan)) ? r.result.plan : [], usage, review: null };
  }

  const submitTool = { name: 'submit_milestone', description: 'Submit the finished atomic sub-issues for the CURRENT milestone. You will then be asked for the next milestone.', input_schema: obj({ issues: arr(ISSUE_OBJ, ISSUES_DESC) }, ['issues']) };
  const tools = EXPLORE_TOOLS.concat([submitTool]);
  const results = [];          // [{ milestone, issues }]
  let knowledge = '';          // carry-over handoff notes after a compaction
  let idx = 0;

  const seed = () => {
    const prior = results.length ? ('\n\n=== ISSUES ALREADY CREATED (do NOT duplicate — build on them) ===\n' + JSON.stringify(results.flatMap((r) => r.issues.map((i) => ({ milestone: r.milestone, title: i.title, objective: i.objective }))), null, 2)) : '';
    const know = knowledge ? ('\n\n=== HANDOFF NOTES — what you already learned about this codebase ===\n' + knowledge) : '';
    const task = '\n\n=== YOUR TASK ===\nPlan the build as atomic, governance-phased Linear sub-issues, ONE MILESTONE AT A TIME, in order. Plan THIS milestone now: "' + milestones[idx].name + '"' + (milestones[idx].done ? ' — done means: ' + milestones[idx].done : '') + '. Explore the code first, then call submit_milestone.';
    return [{ role: 'user', content: intakeBrief(intake) + govBlock + manifestBlock(index) + prior + know + task }];
  };

  const mlabel = (i) => 'Milestone ' + (i + 1) + '/' + milestones.length + ': ' + milestones[i].name;
  emit(onProgress, { t: 'start', label: mlabel(0), agent: true });
  let msTok = { fresh: 0, cached: 0, output: 0 };
  let messages = seed();
  let steps = 0;
  while (idx < milestones.length && steps < 500) {
    bail(checkCancel);
    steps++;
    const data = await agentFetch(apiKey, PLAN_SYSTEM_AGENT, tools, messages, PLAN_MAX_TOKENS);
    const ct = cacheTok(data);
    const outTok = (data && data.usage && data.usage.output_tokens) || 0;
    msTok.fresh += ct.fresh + ct.write; msTok.cached += ct.read; msTok.output += outTok;
    const lastInput = ct.fresh + ct.write + ct.read;   // full context size (for the compaction trigger)
    usage.push({ pass: 'plan · ' + milestones[idx].name, input: ct.fresh + ct.write, cacheRead: ct.read, output: outTok, max: PLAN_MAX_TOKENS });
    const blocks = (data && data.content) || [];
    messages.push({ role: 'assistant', content: blocks });
    const tus = blocks.filter((b) => b.type === 'tool_use');
    if (!tus.length) { messages.push({ role: 'user', content: 'Explore if needed, then call submit_milestone with the issues for "' + milestones[idx].name + '".' }); continue; }
    const sub = tus.find((t) => t.name === 'submit_milestone');
    if (!sub) emit(onProgress, { t: 'activity', detail: mlabel(idx) + ' — ' + describeTools(tus), tokens: msTok, agent: true });
    const rb = [];
    for (const t of tus) {
      if (t.name === 'submit_milestone') continue;
      let out; try { out = await exec(t.name, t.input); } catch (e) { out = 'error: ' + (e.message || e); }
      rb.push({ type: 'tool_result', tool_use_id: t.id, content: String(out).slice(0, 80000) });
    }
    if (sub) {
      const issues = Array.isArray(sub.input.issues) ? sub.input.issues : [];
      results.push({ milestone: milestones[idx].name, issues: issues });
      emit(onProgress, { t: 'done', label: mlabel(idx), tokens: msTok, note: issues.length + ' issues · ctx ' + Math.round(lastInput / 1000) + 'K' });
      msTok = { fresh: 0, cached: 0, output: 0 };
      idx++;
      rb.push({ type: 'tool_result', tool_use_id: sub.id, content: idx < milestones.length ? ('Recorded ' + issues.length + ' issues. Now plan the next milestone: "' + milestones[idx].name + '"' + (milestones[idx].done ? ' — done means: ' + milestones[idx].done : '') + '. Reuse what you already read; only read NEW files if needed.') : 'Recorded. All milestones planned — you are done.' });
      if (idx < milestones.length) emit(onProgress, { t: 'start', label: mlabel(idx), agent: true });
    }
    messages.push({ role: 'user', content: rb });
    if (sub && idx < milestones.length && lastInput > COMPACT_THRESHOLD) {
      emit(onProgress, { t: 'start', label: 'Compacting context (~' + Math.round(lastInput / 1000) + 'K) → handoff notes', agent: true });
      try { knowledge = await compactKnowledge(apiKey, messages, tools, usage); } catch (e) {}
      messages = seed();
      emit(onProgress, { t: 'start', label: mlabel(idx), agent: true });
    }
  }

  let review = null;
  try { review = await cohesionReview(apiKey, intake, index, gov, results, usage, onProgress, checkCancel); }
  catch (e) { if (e && e.cancelled) throw e; console.log('[enrich] cohesion review failed: ' + (e.message || e)); }

  // Every milestone ends with a HUMAN close-out gate: open the milestone's PR and merge
  // it after review. Added deterministically (last issue per milestone) so it's always
  // present and a person must close it before the milestone is done.
  results.forEach((g) => {
    if (!Array.isArray(g.issues)) g.issues = [];
    g.issues.push({
      owner: 'Human',
      title: 'Review & merge the PR for "' + g.milestone + '"',
      objective: 'Human close-out gate — review the milestone\'s changes and merge the PR; the milestone is not done until this is closed.',
      steps: [
        'Open the pull request for this milestone\'s branch against `main` (push it first if the agent has not).',
        'Review the full diff and confirm the milestone\'s done-when acceptance criteria are met.',
        'Confirm CI and the cross-examiner gate pass on the PR.',
        'Merge the PR, delete the branch, and close the milestone\'s issues.',
      ],
      notes: 'The human sign-off that closes the milestone — do not skip it even if the work looks complete.',
      doneWhen: 'The milestone\'s PR is merged to `main` and its issues are closed.',
      label: 'gov:phase-07-release',
    });
  });

  return { plan: results, usage, review };
}

module.exports = { enrich, enrichArchitecture, enrichPlan, aiEnabled, ENRICH_SCHEMA, MODEL, GOV_LABELS };
